### ISSUE TITLE
union support?

### ISSUE THREAD

**Issue by chris1seto** [andreax79/python-cstruct#10]
First off, I love this library! 

Just wondering if any possibility of unions within structs would be supported eventually?

**Comment by andreax79** [comment]
Yes, i'm working on it. The version in the dev_union branch support unpack but not yet pack.

**Comment by chris1seto** [comment]
Awesome! Thanks a bunch! I use your library all over the place. It's extremely handy.

**Comment by andreax79** [comment]
Union are supported in MemCStruct since version 2.1
