### ISSUE TITLE
comparing a AbstractCStruct based object against None fails with a AttributeError

### ISSUE THREAD

**Issue by bearsh** [andreax79/python-cstruct#13]
doing something like
```python
class C(CStruct):
    __def__ = "struct { char i; }"

c = C()
c == None
```
raise an `AttributeError: type object 'C' has no attribute '_abc_impl'`

`isinstance()` in the following code can not handle a `None` object 

https://github.com/andreax79/python-cstruct/blob/cedb0c9b4ae769b65de7c6cf8405e98361cc7445/cstruct/abstract.py#L144

maybe this can be changed to something like:
```python
return other is not None and isinstance(other, self.__class__) and self.__dict__ == other.__dict__ 
```

a simple workaround (and probably better style) is to use `c is None` instead of `c == None`

**Comment by andreax79** [comment]
Thanks, fixed in v2.3
