### ISSUE TITLE
Support for enums

### ISSUE THREAD

**Issue by tyalie** [andreax79/python-cstruct#16]
Currently this library doesn't support the `enum eName name` syntax in structs. Would this be a wanted feature or was it left out with reason?

**Comment by tyalie** [comment]
Okay so this was resolved with #18. The thing missing for now is a better document in that code and test cases

**Comment by andreax79** [comment]
Thanks, enums are a new great feature. I have added the enum support to the `cstruct.parse` function, some test cases and  a (minimal) documentation. Please check if the enum documentation is ok.
I have noticed that `cstruct.sizeof("enum X")` does not work, and I wonder if you if possible to support it.

**Comment by tyalie** [comment]
What would you expect as an output?

**Comment by tyalie** [comment]
I've also looked at the commits and they look good. I think I would add a test case for unnamed enums, but otherwise its relatively comprehensive.

**Comment by andreax79** [comment]
> What would you expect as an output?
The enum's size in bytes, i.e. __size__

**Comment by tyalie** [comment]
Ah okay so you mean for already defined enums. Yeah I think that would be possible

Sorry that I misunderstood you there. For inline defined enums this would be much harder as compiler defined and such
