### ISSUE TITLE
how do I deal with size_t

### ISSUE THREAD

**Issue by dan-bar-dov** [andreax79/python-cstruct#20]
I have fields in the struct if types that are not in NATIVE_TYPES, from the docs, It is not clear to me how to deal with those

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/cstruct/native_types.py", line 74, in get_native_type
    return NATIVE_TYPES[type_]
KeyError: 'size_t'

**Comment by andreax79** [comment]
Could you provide your code please?

**Comment by dan-bar-dov** [comment]
I figured out that in order to define simple types I need the following:
class SizeT(AbstractNativeType):
    type_name = "size_t"
    native_format = "Q"
