### ISSUE TITLE
question: how do I access annonymous fields

### ISSUE THREAD

**Issue by dan-bar-dov** [andreax79/python-cstruct#22]
I have a struct that looks like this:

```
struct op {
  char preamble[10];
  uint64_t magic;
  union {
      struct op_a a_op;
      struct op_b b_op;
  };
};
```

now if I access op.a_op the contents of a_op is corrupted. I see that under __annonymous0, a_op content is correctly aligned. but I cannot access op.__annonymous0.a_op

what am I missing?

**Comment by andreax79** [comment]
It's `op.__anonymous0.a_op` , with a single 'n'... but I didn't understand which data is corrupted. Are the a_op/b_op not correctly aligned?

**Comment by dan-bar-dov** [comment]
when I pass the object to a method on another class, op.__anonymous.a_op raises. You can see that for some reason it complains about _Controller__anonymous0, Controller is the class that received the FsiOperationLog as parameter. I looks like the anonymous access is broken?
The 0xdeadbeef is in the preamble - accessed without __anonymous, and works fine.

```
[INFO] 2022-11-22 17:45:45,514 fscp controller handle_create[255]: type=<class 'src.fsi.structs.FsiOperationLog'>
[INFO] 2022-11-22 17:45:45,514 fscp controller handle_create[256]: 0xdeadbeef
Traceback (most recent call last):
  File "/App/src/fscp/fscp.py", line 241, in <module>
    main()
  File "/App/src/fscp/fscp.py", line 236, in main
    rc = run(args.func(args))
  File "/App/src/fscp/fscp.py", line 191, in run
    fsi_drainer()
  File "/App/src/fscp/fscp.py", line 184, in fsi_drainer
    handler(fsi_op)
  File "/App/src/fscp/controller.py", line 257, in handle_create
    logger.info(f"{x.__anonymous0.creat.name}")
  File "/usr/local/lib/python3.10/dist-packages/cstruct/mem_cstruct.py", line 118, in __getattr__
    field_type = self.__fields_types__[attr]
KeyError: '_Controller__anonymous0'
```

**Comment by andreax79** [comment]
Please check if it works correctly with a named union, e.g.
```
struct op {
  char preamble[10];
  uint64_t magic;
  union {
      struct op_a a_op;
      struct op_b b_op;
  } union0;
};
```
It it works there is a problem with the unions.
