### ISSUE TITLE
Low performance with large set of strucures

### ISSUE THREAD

**Issue by jpgreninger** [andreax79/python-cstruct#24]
Hi there,

I'm using cstruct to model packet headers in a simulation. We have C structures that model the different headers and then a packet structure that models the header stack for the packet. We are reading PCAP files captured from a real network, reading them in using SCAPY, creating the PKT structure that is wrapped in cstruct, populating the PKT structure, packing it, the writing to a gzipped binary file. Here's an image of the performance we see from cstruct from SPIDERVIZ. Is this typical or are we doing something incorrect? Previously we were reading the PCAP files, parsing them and writing the information to a text file. For the same PCAP file with 16k packets, the processing time went from 11 seconds to 4 hours

<img width="818" alt="snakeViz" src="https://user-images.githubusercontent.com/29163423/228360928-07cafd2e-16b5-40aa-a57e-fcec67946dbd.png">

Thanks for your help

**Comment by andreax79** [comment]
Hi,

As a quick test, you can try replacing `cstruct.MemCStruct` with `ccstruct.CStruct`, generally the performance are much better.

**Comment by jpgreninger** [comment]
Sure, I'll let you know how long it runs

 

From: Andrea Bonomi ***@***.***> 
Sent: Wednesday, March 29, 2023 1:36 AM
To: andreax79/python-cstruct ***@***.***>
Cc: John Greninger ***@***.***>; Author
***@***.***>
Subject: Re: [andreax79/python-cstruct] Low performance with large set of
strucures (Issue #24)

 

Hi,

As a quick test, you can try replacing cstruct.MemCStruct with
ccstruct.CStruct, generally the performance are much better.

-
Reply to this email directly, view it on GitHub
<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com
%2Fandreax79%2Fpython-cstruct%2Fissues%2F24%23issuecomment-1488167307&data=0
5%7C01%7C%7Cfd1a5cbea7bf41fe4a5f08db3030a64e%7C84df9e7fe9f640afb435aaaaaaaaa
aaa%7C1%7C0%7C638156757733890672%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDA
iLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xKGk2A
u3Q2uKP6c2fpBhH0l6udHkroeLTJK7kvL5J50%3D&reserved=0> , or unsubscribe
<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com
%2Fnotifications%2Funsubscribe-auth%2FAG6P7H6AXGPG4BD4OLXLYMLW6PX7VANCNFSM6A
AAAAAWLCFBYU&data=05%7C01%7C%7Cfd1a5cbea7bf41fe4a5f08db3030a64e%7C84df9e7fe9
f640afb435aaaaaaaaaaaa%7C1%7C0%7C638156757733890672%7CUnknown%7CTWFpbGZsb3d8
eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C
%7C%7C&sdata=%2FKq%2BYKslxgHPjHZ%2Bi31h%2BQhRq1TW6vNFJGY88no9ElE%3D&reserved
=0> .
You are receiving this because you authored the thread.
<https://github.com/notifications/beacon/AG6P7H4YM3B3LWQGAG2KESDW6PX7VA5CNFS
M6AAAAAAWLCFBYWWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTS
YWOQYW.gif> Message ID:
***@***.***
***@***.***> >
